import "../styles/globals.css";
import { Abril_Fatface, Inter } from "next/font/google";

const inter = Inter({
	subsets: ["latin"],
	display: "swap",
	weight: ["500", "700"],
	variable: "--font-inter",
});

const abrilFatface = Abril_Fatface({
	subsets: ["latin"],
	weight: "400",
	display: "swap",
	variable: "--font-abril",
});

const RootLayout = ({ children }: { children: React.ReactNode }) => {
	return (
		<html data-theme="light" className={`${inter.variable} ${abrilFatface.variable}`}>
			<body>
				<h1>Hello there</h1>
				{children}
			</body>
		</html>
	);
};

export const metadata = {
	title: "Welcome to dostoevsky",
	description: "Generated by create-nx-workspace",
};

export default RootLayout;
